
const columns = [
  {name: "Fecha", uid: "date"},
  {name: "No Pedido", uid: "orderNumber"},
  {name: "Cantidad", uid: "quantity"},
  {name: "Material", uid: "material"},
  {name: "Precio total", uid: "totalPrice"},
  {name: "SAG", uid: "sag"},
  {name: "Impresor", uid: "trade"},
  {name: "Status", uid: "status"},
  {name: "Estado de pedido", uid: "orderStatus"},
  {name: "", uid: "actions"},
];

const users = [
  {
    id: 1,
    date: "30/10/2023",
    orderNumber: "000006-1",
    quantity: "100",
    material: "Pancartas",
    totalPrice: "$9900",
    sag: "Agencia 1",
    trade: "Impresor 001",
    status: "Pendiente",
    orderStatus: "Pendiente",
  },
  {
    id: 2,
    date: "31/10/2023",
    orderNumber: "000006-1",
    quantity: "100",
    material: "Pancartas",
    totalPrice: "$9900",
    sag: "Agencia 1",
    trade: "Impresor 001",
    status: "Pendiente",
    orderStatus: "Pendiente",
  },
  {
    id: 3,
    date: "32/10/2023",
    orderNumber: "000006-1",
    quantity: "100",
    material: "Pancartas",
    totalPrice: "$9900",
    sag: "Agencia 1",
    trade: "Impresor 001",
    status: "Pendiente",
    orderStatus: "Pendiente",
  },
  {
    id: 4,
    date: "33/10/2023",
    orderNumber: "000006-1",
    quantity: "100",
    material: "Pancartas",
    totalPrice: "$9900",
    sag: "Agencia 1",
    trade: "Impresor 001",
    status: "Pendiente",
    orderStatus: "Pendiente",
  },
  {
    id: 5,
    date: "34/10/2023",
    orderNumber: "000006-1",
    quantity: "100",
    material: "Pancartas",
    totalPrice: "$9900",
    sag: "Agencia 1",
    trade: "Impresor 001",
    status: "Pendiente",
    orderStatus: "Pendiente",
  },
];

export {columns, users};