apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maz-formlandings-front.name" . }}-config
  namespace: {{ .Values.devops.app.env }}
data:
  nginx.conf: |-
    {{- .Files.Get "nginx.conf" | nindent 4 }}